### ISSUE TITLE
Cannot find module 'babel/polyfill'

### ISSUE THREAD

**Issue by slapers** [75lb/command-line-args#11]
Hi,

I have the following source:

```javascript
  "use strict";
  
  let fs = require('readdirp'),
      es = require('event-stream'),
      commandLineArgs = require("command-line-args");
  
  
  let cli = commandLineArgs([
      { name: "verbose", alias: "v", type: Boolean },
      { name: "src", type: String, multiple: true, defaultOption: true },
      { name: "timeout", alias: "t", type: Number }
  ]);
  
  let options = cli.parse();
```

When running this with iojs i get the following error:

```shell
  Error: Cannot find module 'babel/polyfill'
      at Function.Module._resolveFilename (module.js:336:15)
      at Function.Module._load (module.js:286:25)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (xxxxxxx/node_modules/command-line-args/es5/command-line-args.js:7:1)
      at Module._compile (module.js:430:26)
      at Object.Module._extensions..js (module.js:448:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
```

Node  (iojs) and npm versions:

```
➜  node -v
v3.0.0
➜  npm -v
2.13.3

```
best,
Stefan

**Comment by 75lb** [comment]
my apologies, please update/reinstall the module and try again.. it was an issue with the dependencies.

**Comment by slapers** [comment]
Hey,

No need to apologise :-) Great module !!
Reinstalled and its working !

thanks,
Stefan

**Comment by 75lb** [comment]
good.. pleased you like it :)
