### ISSUE TITLE
When trying to use a proxy such as jFrog's Artifactory, npm install fails

### ISSUE THREAD

**Issue by corydorning** [75lb/command-line-args#111]
Trying to use jFrog Artifactory as my npm registry, which proxies the public npm repsository and for some reason this package fails with the following error:

```
npm http fetch GET 400 https://jfrog.mydomain.com/artifactory/api/npm/npm-virtual/command-line-args/-/command-line-args-5.1.1.tgz 159ms
npm verb stack Error: 400 Bad Request: command-line-args@5.1.1
npm verb stack     at fetch.then.res (D:\node\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
npm verb stack     at tryCatcher (D:\node\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (D:\node\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
npm verb stack     at Promise._settlePromise (D:\node\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (D:\node\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
npm verb stack     at Promise._settlePromises (D:\node\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
npm verb stack     at Async._drainQueue (D:\node\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
npm verb stack     at Async._drainQueues (D:\node\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues (D:\node\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm verb stack     at runCallback (timers.js:810:20)
npm verb stack     at tryOnImmediate (timers.js:768:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
...
npm verb node v8.12.0
npm verb npm  v6.4.1
npm ERR! code E400
npm ERR! 400 Bad Request: command-line-args@5.1.1
```

Oddly enough,  its the only one that fails out of over 60 modules. If i remove this module from package.json, npm install runs fine.

**Comment by corydorning** [comment]
Occasionally, it gets passed the 400 Bad Request and I get this:
```
npm verb stack Error: 404 Not Found: array-back@^3.0.1
npm verb stack     at fetch.then.res (D:\node\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
npm verb stack     at tryCatcher (D:\node\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (D:\node\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
npm verb stack     at Promise._settlePromise (D:\node\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (D:\node\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
npm verb stack     at Promise._settlePromises (D:\node\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
npm verb stack     at Async._drainQueue (D:\node\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
npm verb stack     at Async._drainQueues (D:\node\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues (D:\node\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm verb stack     at runCallback (timers.js:810:20)
npm verb stack     at tryOnImmediate (timers.js:768:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
npm verb cwd D:\CBJ\a7c97ac5\workspace\mple-application_develop-BD-pass
npm verb Windows_NT 10.0.14393
npm verb argv "D:\\node\\node.exe" "D:\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose"
npm verb node v8.12.0
npm verb npm  v6.4.1
npm ERR! code E404
npm ERR! 404 Not Found: array-back@^3.0.1
```

**Comment by 75lb** [comment]
I'm sorry, this is beyond my control and not something i can fix.. command-line-args installs fine using npm.
