### ISSUE TITLE
cli.parse() is not a function

### ISSUE THREAD

**Issue by wjrivera** [75lb/command-line-args#22]
I've installed command-line-args and compiled a basic code for passing arguments in cli to do a mongodb request.  I get this error at runtime.

```
  var options = cli.parse()
                    ^
TypeError: cli.parse is not a function
    at commandLineOptions (C:\MCS-Node\MCS-Node\mongo.js:64:21)
    at Object.<anonymous> (C:\MCS-Node\MCS-Node\mongo.js:6:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

Any help? ty

Node version: 4.4.7
NPM version: 3.10.5
Mongo version: 3.2.8
Windows 7 Pro

**Comment by wjrivera** [comment]
Never mind, should have check your releases in<br>
https://github.com/75lb/command-line-args/releases<br>
Thank you so much!!!
