### ISSUE TITLE
Weird error as soon as I require library

### ISSUE THREAD

**Issue by kristianmandrup** [75lb/command-line-args#29]
Call stack, entry point from my code: `easy-coveralls/server.js:11:25`

`const commandLineArgs = require('command-line-args')`

So it fails as soon as I require it!?

```
/Users/kristianmandrup/repos/node-libs/easy-coveralls/node_modules/command-line-args/lib/command-line-args.js Error
  at new JS_Parse_Error (<anonymous>:1545:18)
  ...
  at Instrument.process (/Users/kristianmandrup/repos/node-libs/easy-coveralls/node_modules/jscoverage/lib/instrument.js:61:22)
  at Object.exports.process (/Users/kristianmandrup/repos/node-libs/easy-coveralls/node_modules/jscoverage/lib/jscoverage.js:133:18)
  at Object.Module._extensions..js (/Users/kristianmandrup/repos/node-libs/easy-coveralls/node_modules/jscoverage/lib/patch.js:106:28)
  at Module.require (/Users/kristianmandrup/repos/node-libs/easy-coveralls/node_modules/jscoverage/lib/patch.js:76:30)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/kristianmandrup/repos/node-libs/easy-coveralls/node_modules/command-line-args/index.js:61:22)
  at Module._compile (module.js:573:32)
  at Object.Module._extensions..js (/Users/kristianmandrup/repos/node-libs/easy-coveralls/node_modules/jscoverage/lib/patch.js:115:12)
  at Module.require (/Users/kristianmandrup/repos/node-libs/easy-coveralls/node_modules/jscoverage/lib/patch.js:76:30)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/kristianmandrup/repos/node-libs/easy-coveralls/server.js:11:25)
```

**Comment by kristianmandrup** [comment]
Sorry, it works on a one liner. Some other weird shit going on in `easy-coveralls` that I can't yet track.
