### ISSUE TITLE
definitions.load is not a function

### ISSUE THREAD

**Issue by crobinson42** [75lb/command-line-args#41]
Here's my setup:

```
const commandLineArgs = require('command-line-args')

const clargsDefinitions = [
	{ name: 'reduxLogger', alias: 'r', type: Boolean, defaultOption: false },
]

const options = commandLineArgs(clargsDefinitions)

export default options
```

Here's the error:
```
TypeError: definitions.load is not a function
      
      at commandLineArgs (node_modules/command-line-args/lib/command-line-args.js:37:15)
      at Object.<anonymous> (config/clargs.js:9:15)
      at Object.<anonymous> (app/store.js:11:41)
      at Object.<anonymous> (tests/Store.test.js:1:409)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:744:12)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by crobinson42** [comment]
env issue?! fml
