### ISSUE TITLE
TypeError: def.isBoolean is not a function

### ISSUE THREAD

**Issue by ronyad** [75lb/command-line-args#42]
Hey Im using node 6.3.0
When I ran the following command 

 node RecordingSourceOnly.js -t 5

where  RecordingSourceOnly.js is 

const commandLineArgs = require('command-line-args')

const optionDefinitions = [
    { name: 'verbose', alias: 'v', type: Boolean },
    { name: 'src', type: String, multiple: true, defaultOption: true },
    { name: 'timeout', alias: 't', type: Number }
]
const options = commandLineArgs(optionDefinitions)
 
I got 

    if (def.isBoolean()) {
            ^

TypeError: def.isBoolean is not a function
    at Output.set (/Users/ron.yadgar/Documents/Repositories/liveDVR/node_modules/command-line-args/lib/output.js:67:13)
    at argv.forEach.arg (/Users/ron.yadgar/Documents/Repositories/liveDVR/node_modules/command-line-args/lib/command-line-args.js:50:27)
    at Argv.forEach (native)
    at commandLineArgs (/Users/ron.yadgar/Documents/Repositories/liveDVR/node_modules/command-line-args/lib/command-line-args.js:48:8)
    at Object.<anonymous> (/Users/ron.yadgar/Documents/Repositories/liveDVR/lib/recording/RecordingSourceOnly.js:32:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by 75lb** [comment]
i can't reproduce your issue - when i run the same code it works fine.. please try deleting then re-installing all npm modules.

**Comment by 75lb** [comment]
confirmed - thanks for letting me know what caused the issue.. I recommend you no longer use q-io until [this issue](https://github.com/kriskowal/q-io/issues/160) is fixed.

**Comment by 75lb** [comment]
consider this lightweight `fs` library which uses promises: https://github.com/75lb/fs-then-native
